FUNCTION-POOL zdedu_liquidacion_pago_fm.    "MESSAGE-ID ..

* INCLUDE LZDEDU_LIQUIDACION_PAGO_FMD...     " Local class definition

CONSTANTS: co_x(1)    TYPE c VALUE 'X',
           co_o(1)    TYPE c VALUE 'O',
           co_a(1)    TYPE c VALUE 'A',
           co_e(1)    TYPE c VALUE 'E',
           co_i(1)    TYPE c VALUE 'I',
           co_d(1)    TYPE c VALUE 'D',
           co_u(1)    TYPE c VALUE 'U',
           co_s(1)    TYPE c VALUE 'S',
           co_o*(2)   TYPE c VALUE 'O*',
           co_d*(2)   TYPE c VALUE 'D*',
           co_pp(2)   TYPE c VALUE 'PP',
           co_eq(2)   TYPE c VALUE 'EQ',
           co_01(2)   TYPE c VALUE '01',
           co_sm(2)   TYPE c VALUE 'SM',
           co_cs(2)   TYPE c VALUE 'CS',
           co_sc(2)   TYPE c VALUE 'SC',
           co_st(2)   TYPE c VALUE 'ST',
           co_es(2)   TYPE c VALUE 'ES',
           co_raw(3)  TYPE c VALUE 'RAW',
           co_pdf(3)  TYPE c VALUE 'PDF',
           co_cop(3)  TYPE c VALUE 'COP',
           co_517(3)  TYPE c VALUE '517',
           co_text(4) TYPE c VALUE 'TEXT',
           co_0800(4) TYPE c VALUE '0800',
           co_lp01(4) TYPE c VALUE 'LP01',
           co_locl(4) TYPE c VALUE 'LOCL',
           co_pdf2(4) TYPE c VALUE 'PDF2'.

TYPES: BEGIN OF tys_contratos,
         opbel    TYPE dfkkop-opbel,
         vtref    TYPE dfkkop-vtref,
         blart    TYPE dfkkop-blart,
         hvorg    TYPE dfkkop-hvorg,
         psobtyp  TYPE dfkkop-psobtyp,
         vktyp_ps TYPE dfkkop-vktyp_ps, " MOD 21-12-2016
         optxt    TYPE dfkkop-optxt,    " MOD 21-12-2016
         betrw    TYPE dfkkop-betrw,
         psgrant  TYPE dfkkop-psgrant,
         psobtypt TYPE tpsob001t-psobtypt,
       END OF tys_contratos,

       BEGIN OF tys_zpre_admi1,
         nombre       TYPE zpre_admi_1-nombre,
         sdo_nombre   TYPE zpre_admi_1-sdo_nombre,
         apellido     TYPE zpre_admi_1-apellido,
         sdo_apellido TYPE zpre_admi_1-sdo_apellido,
         tipo_documen TYPE zpre_admi_1-tipo_documen,
         nro_documen  TYPE zpre_admi_1-nro_documen,
       END OF tys_zpre_admi1,

       BEGIN OF tys_hrp1001,
         objid TYPE hrp1001-objid,
         sobid TYPE hrp1001-sobid,
       END OF tys_hrp1001,

       BEGIN OF tys_cmacdb_feefica,
         docnr  TYPE cmacdb_feefica-docnr,
         itemnr TYPE cmacdb_feefica-itemnr,
         opbel  TYPE cmacdb_feefica-opbel,
         inters TYPE check,
         sortf  TYPE n LENGTH 3,
       END OF tys_cmacdb_feefica,

       BEGIN OF tys_cmacdb_feesm,
         docnr         TYPE cmacdb_feefica-docnr,
         itemnr        TYPE cmacdb_feefica-itemnr,
         cmsmid        TYPE cmacdb_feesm-cmsmid,
         cmcrhrs       TYPE cmacdb_feesm-cmcrhrs,
         cmsmvalue     TYPE cmacdb_feesm-cmsmvalue,
         objid         TYPE hrobjid,
         objid_itemres TYPE cmacdb_itemres-objid,
         stext         TYPE hrp1000-stext,
       END OF tys_cmacdb_feesm,

       BEGIN OF tys_cmacdb_itemres,
         docnr         TYPE cmacdb_itemres-docnr,
         itemnr        TYPE cmacdb_itemres-itemnr,
         otype         TYPE cmacdb_itemres-otype,
         objid         TYPE cmacdb_itemres-objid,
         acc_key       TYPE cmacdb_itemres-acc_key,
         docamt        TYPE cmacdb_itemres-docamt,
         stext         TYPE hrp1000-stext,
         objid_hrp1000 TYPE hrp1000-objid,
       END  OF tys_cmacdb_itemres,

       BEGIN OF tys_contr_liqui,
         psobtyp TYPE zedu_contr_liqui-psobtyp,
       END OF tys_contr_liqui,

       BEGIN OF tys_range_psobtyp,
         sign   TYPE char1,
         option TYPE char2,
         low    TYPE dfkkop-psobtyp,
         high   TYPE dfkkop-psobtyp,
       END OF tys_range_psobtyp,

       BEGIN OF tys_fechas,
         ord_date     TYPE datum,
         ord_value    TYPE betrw_kk,
         extra1_date  TYPE datum,
         extra1_value TYPE betrw_kk,
         extra2_date  TYPE datum,
         extra2_value TYPE betrw_kk,
       END OF tys_fechas,

* Begin Modif 13-12-2016
       BEGIN OF tys_dfkkop,
         opbel   TYPE dfkkop-opbel,
         psobtyp TYPE dfkkop-psobtyp,
         optxt   TYPE dfkkop-optxt,
         betrw   TYPE dfkkop-betrw,
         hvorg   TYPE dfkkop-hvorg,
         tvorg   TYPE dfkkop-tvorg,
       END OF tys_dfkkop,

       BEGIN OF gty_opbel_persl,
         opbel  TYPE dfkkop-opbel,
         gpart  TYPE dfkkop-gpart,
         persl  TYPE dfkkop-persl,
         blart  TYPE dfkkop-blart,
         stakz  TYPE dfkkop-stakz, "Es documento intersemestral
         vktyp  TYPE dfkkop-vktyp_ps,
         inters TYPE check,
         sortf  TYPE n LENGTH 3,
       END OF gty_opbel_persl,
* End Modif 13-12-2016

       tyt_docs              TYPE STANDARD TABLE OF docs,
       tyt_hrp1001           TYPE STANDARD TABLE OF tys_hrp1001,
       tyt_contratos         TYPE STANDARD TABLE OF tys_contratos,
       tyt_zpre_admi1        TYPE STANDARD TABLE OF tys_zpre_admi1,
       tyt_contr_liqui       TYPE STANDARD TABLE OF tys_contr_liqui,
       tyt_cmacdb_feefica    TYPE STANDARD TABLE OF tys_cmacdb_feefica,
       tyt_cmacdb_feesm      TYPE STANDARD TABLE OF tys_cmacdb_feesm,
       tyt_cmacdb_itemres    TYPE STANDARD TABLE OF tys_cmacdb_itemres,
       tyt_dfkkop            TYPE STANDARD TABLE OF tys_dfkkop,
       gty_t_opbel_persl     TYPE STANDARD TABLE OF gty_opbel_persl,
       gty_t_opbel_contratos TYPE STANDARD TABLE OF opbel_kk.

DATA: gt_main            TYPE zedu_t_liquidacion_pago_items,
      gs_header          TYPE zedu_s_liquidacion_pago_header,
      gv_total           TYPE betrw_kk,
      gv_total_extr      TYPE betrw_kk,
      gv_fecha_cuota_ini TYPE d.
