*&---------------------------------------------------------------------*
*&  Include           ZDIEDU_ASIGNAR_TITULACION_T
*&---------------------------------------------------------------------*

TYPES:
  BEGIN OF gty_datos,
    stobjid          TYPE piqstudent,
    csobjid          TYPE piqcsobjid,
    scobjid          TYPE piqscobjid,
    student12        TYPE piqstudent12,
    nombre_comp      TYPE zedua_name,
    tipo_doc         TYPE ztipdoc,
    nro_doc          TYPE bu_id_number,
    lug_exp          TYPE zedua_lugced,
    apoderado        TYPE zeduapo,
    fecha_fin_seg    TYPE datum,
    titulo           TYPE ztitulo,
    acto             TYPE zacto,
    acta             TYPE zacta,
    libro            TYPE zlibro,
    folio            TYPE zfolio,
    diploma          TYPE zdiploma,
    resolu           TYPE zresolu,
    fecact           TYPE zfecact,
    insc_per         TYPE zinsc_per,
    puesto_cohorte   TYPE zpuesto_cohorte,
    puesto_acto      TYPE zpuesto_acto,
    estud_coho_grad  TYPE zestud_coho_grad,
    estudiantes_coho TYPE zestudiantes_coho,
    estudiantes_acto TYPE zestudiantes_acto,
    promed           TYPE zpromed,
    noasistio        TYPE znoasistio,
    hrp9117          TYPE abap_bool,
    fin_segmento     TYPE abap_bool,
    zedu_estacto     TYPE abap_bool,
  END OF gty_datos,

  BEGIN OF gty_log,
    stobjid     TYPE piqstudent,
    csobjid     TYPE piqcsobjid,
    scobjid     TYPE piqscobjid,
    student12   TYPE piqstudent12,
    nombre_comp TYPE zedua_name,
    tipo_doc    TYPE ztipdoc,
    nro_doc     TYPE bu_id_number,
    mensaje     TYPE string,
  END OF gty_log,

  gtyt_datos TYPE TABLE OF gty_datos,
  gtyt_log   TYPE TABLE OF gty_log.
