*&---------------------------------------------------------------------*
*&  Include           ZDIEDU_EXTR_CERT_ACAD_T
*&---------------------------------------------------------------------*

*&---------------------------------------------------------------------*
*   Declaracion de estructuras de datos
*&---------------------------------------------------------------------*
TYPES:
  BEGIN OF gty_c_param,
    idparam    TYPE zies_idparam,
    idparampos TYPE zies_idparam_pos,
    valor      TYPE zies_valor,
  END OF gty_c_param,

  BEGIN OF gty_r_blart,
    sign   TYPE ddsign,
    option TYPE ddoption,
    low    TYPE blart_kk,
    high   TYPE blart_kk,
  END OF gty_r_blart,

  BEGIN OF gty_r_psobtyp,
    sign   TYPE ddsign,
    option TYPE ddoption,
    low    TYPE psobtyp_ps,
    high   TYPE psobtyp_ps,
  END OF gty_r_psobtyp,

  BEGIN OF gty_r_augrd,
    sign   TYPE ddsign,
    option TYPE ddoption,
    low    TYPE augrd_kk,
    high   TYPE augrd_kk,
  END OF gty_r_augrd,

  BEGIN OF gty_r_hvorg,
    sign   TYPE ddsign,
    option TYPE ddoption,
    low    TYPE hvorg_kk,
    high   TYPE hvorg_kk,
  END OF gty_r_hvorg,

  BEGIN OF gty_r_tvorg,
    sign   TYPE ddsign,
    option TYPE ddoption,
    low    TYPE tvorg_kk,
    high   TYPE tvorg_kk,
  END OF gty_r_tvorg,

  gty_ctrlcert    TYPE zedu_ctrlcert,

  gty_certacad_h  TYPE zedu_certacad_h,

  gty_certacad_pe TYPE zedu_certacad_pe,

  gty_certacad_pm TYPE zedu_certacad_pm,

  gty_certacad_sm TYPE zedu_certacad_sm,

  gty_certacad_na TYPE zedu_certacad_na,

  gty_certacad_ps TYPE zedu_certacad_ps,

  gty_certacad_ro TYPE zedu_certacad_ro,

  gty_certacad_gr TYPE zedu_certacad_gr,

  BEGIN OF gty_cmacbpst,
    partner   TYPE bu_partner,
    student12 TYPE piqstudent12,
    stobjid   TYPE piqstudent,
  END OF gty_cmacbpst,

  BEGIN OF gty_but0id,
    partner         TYPE bu_partner,
    type            TYPE bu_id_type,
    idnumber        TYPE bu_id_number,
    institute       TYPE bu_id_institute,
    entry_date      TYPE bu_id_entry_date,
    valid_date_from TYPE bu_id_valid_date_from,
    valid_date_to   TYPE bu_id_valid_date_to,
  END OF gty_but0id,

  BEGIN OF gty_hrp1769,
    plvar        TYPE plvar,
    otype        TYPE otype,
    objid        TYPE hrobjid,
    subty        TYPE subtyp,
    istat        TYPE istat_d,
    begda        TYPE begdatum,
    endda        TYPE enddatum,
    varyf        TYPE varyf,
    seqnr        TYPE seqnr,
    otjid        TYPE otjid,
    beg_process  TYPE piqprocess_beg,
    beg_reason   TYPE piqprocreason,
    beg_key_date TYPE piqregdate,
    end_process  TYPE piqprocess_end,
    end_reason   TYPE piqderreason,
    end_key_date TYPE piqderdate,
  END OF gty_hrp1769,

  BEGIN OF gty_hrp1001,
    otype   TYPE otype,
    objid   TYPE hrobjid,
    plvar   TYPE plvar,
    rsign   TYPE rsign,
    relat   TYPE relat,
    istat   TYPE istat_d,
    priox   TYPE priox,
    begda   TYPE begdatum,
    endda   TYPE enddatum,
    varyf   TYPE varyf,
    seqnr   TYPE seqnr,
    otjid   TYPE otjid,
    subty   TYPE subtyp,
    sclas   TYPE sclas,
    sobid   TYPE sobid,
    adatanr TYPE hradatanr,
  END OF gty_hrp1001,

  BEGIN OF gty_otjid_varyf,
    otjid TYPE otjid,
    varyf TYPE varyf,
  END OF gty_otjid_varyf,

  BEGIN OF gty_otjid,
    otjid TYPE otjid,
  END OF gty_otjid,

  BEGIN OF gty_hrpad530,
    adatanr      TYPE hradatanr,
    adm_ayear    TYPE piqperyr,
    adm_perid    TYPE piqperid,
    adm_aclevel  TYPE piqlevel,
    adm_categ    TYPE piqadm_categ,
    adm_enrcateg TYPE piqenrcateg,
    adm_recpt    TYPE piqadm_recpt,
  END OF gty_hrpad530,

  BEGIN OF gty_hrp1771,
    plvar     TYPE plvar,
    otype     TYPE otype,
    objid     TYPE hrobjid,
    subty     TYPE subtyp,
    istat     TYPE istat_d,
    begda     TYPE begdatum,
    endda     TYPE enddatum,
    varyf     TYPE varyf,
    seqnr     TYPE seqnr,
    otjid     TYPE otjid,
    ayear     TYPE piqperyr,
    perid     TYPE piqperid,
    pr_status TYPE piqreg_periodstatus,
    prs_state TYPE piqreg_prs_state,
    reason    TYPE piqleareason,
    aclevel   TYPE piqlevel,
    regdate   TYPE piqregperdate,
    cancdate  TYPE piqregcancdate,
  END OF gty_hrp1771,

  BEGIN OF gty_hrp1730,
    plvar     TYPE plvar,
    otype     TYPE otype,
    objid     TYPE hrobjid,
    subty     TYPE subtyp,
    istat     TYPE istat_d,
    begda     TYPE begdatum,
    endda     TYPE enddatum,
    varyf     TYPE varyf,
    seqnr     TYPE seqnr,
    otjid     TYPE otjid,
    optlength TYPE piqlength,
    timeunit  TYPE piqtimeunit,
    snies     TYPE zedu_snies,
  END OF gty_hrp1730,

  BEGIN OF gty_r_otjid,
    sign   TYPE ddsign,
    option TYPE ddoption,
    low    TYPE otjid,
    high   TYPE otjid,
  END OF gty_r_otjid,

  gtyt_r_otjid TYPE TABLE OF gty_r_otjid.

DATA:
  gt_r_otjid  TYPE gtyt_r_otjid.

TYPES:
  BEGIN OF gty_pensum,
    sc_otjid   TYPE otjid,
    sm_r_otjid LIKE gt_r_otjid,
  END OF gty_pensum,

  BEGIN OF gty_adatanr,
    adatanr TYPE hradatanr,
  END OF gty_adatanr,

  BEGIN OF gty_hrp1764,
    plvar TYPE plvar,
    otype TYPE otype,
    objid TYPE hrobjid,
    subty TYPE subtyp,
    istat TYPE istat_d,
    begda TYPE begdatum,
    endda TYPE enddatum,
    varyf TYPE varyf,
    seqnr TYPE seqnr,
    otjid TYPE otjid,
    tabnr TYPE hrtabnr,
  END OF gty_hrp1764,

  BEGIN OF gty_hrt1764,
    tabnr    TYPE hrtabnr,
    tabseqnr TYPE hrtabseqnr,
    pt_otype TYPE otype,
    pt_objid TYPE objektid,
  END OF gty_hrt1764,

  BEGIN OF gty_hrp1735,
    plvar  TYPE plvar,
    otype  TYPE otype,
    objid  TYPE hrobjid,
    subty  TYPE subtyp,
    istat  TYPE istat_d,
    begda  TYPE begdatum,
    endda  TYPE enddatum,
    varyf  TYPE varyf,
    seqnr  TYPE seqnr,
    otjid  TYPE otjid,
    cpmin  TYPE piqcpmin,
    cpmax  TYPE piqcpmax,
    cpunit TYPE piqcpunit,
  END OF gty_hrp1735,

  BEGIN OF gty_hrp1759,
    plvar TYPE plvar,
    otype TYPE otype,
    objid TYPE hrobjid,
    subty TYPE subtyp,
    istat TYPE istat_d,
    begda TYPE begdatum,
    endda TYPE enddatum,
    varyf TYPE varyf,
    seqnr TYPE seqnr,
    infty TYPE infotyp,
    otjid TYPE otjid,
    tabnr TYPE hrtabnr,
  END OF gty_hrp1759,

  BEGIN OF gty_hrt1759,
    tabnr      TYPE hrtabnr,
    tabseqnr   TYPE hrtabseqnr,
    profit_ctr TYPE prctr,
  END OF gty_hrt1759,

  BEGIN OF gty_hrp1732,
    plvar    TYPE plvar,
    otype    TYPE otype,
    objid    TYPE hrobjid,
    subty    TYPE subtyp,
    istat    TYPE istat_d,
    begda    TYPE begdatum,
    endda    TYPE enddatum,
    varyf    TYPE varyf,
    seqnr    TYPE seqnr,
    otjid    TYPE otjid,
    scfeecat TYPE piqscfeecat,
  END OF gty_hrp1732,

  BEGIN OF gty_tabnr,
    tabnr TYPE hrtabnr,
  END OF gty_tabnr,

  BEGIN OF gty_hrpad506,
    adatanr     TYPE hradatanr,
    smstatus    TYPE piqsmstatus,
    cpattemp    TYPE piqcpattemp,
    cpgained    TYPE piqcpgained,
    cpunit      TYPE piqcpunit,
    perid       TYPE piqperid,
    peryr       TYPE piqperyr,
    alt_scaleid TYPE piqscale_id,
    id          TYPE piqmodreg_id,
    pago        TYPE zedu_pago,
  END OF gty_hrpad506,

  BEGIN OF gty_hrp1724,
    plvar     TYPE plvar,
    otype     TYPE otype,
    objid     TYPE hrobjid,
    subty     TYPE subtyp,
    istat     TYPE istat_d,
    begda     TYPE begdatum,
    endda     TYPE enddatum,
    varyf     TYPE varyf,
    seqnr     TYPE seqnr,
    otjid     TYPE otjid,
    modreg_id TYPE piqmodreg_id,
  END OF gty_hrp1724,

  BEGIN OF gty_r_xblnr,
    sign   TYPE ddsign,
    option TYPE ddoption,
    low    TYPE xblnr_kk,
    high   TYPE xblnr_kk,
  END OF gty_r_xblnr,

  gtyt_r_xblnr TYPE TABLE OF gty_r_xblnr.

DATA:
  gt_r_xblnr  TYPE gtyt_r_xblnr.

TYPES:
  BEGIN OF gty_bp_sc_fica,
    gpart   TYPE gpart_kk,
    persl   TYPE persl_kk,
    prctr   TYPE prctr,
    r_xblnr LIKE gt_r_xblnr,
  END OF gty_bp_sc_fica,

  gty_fac_anual TYPE zedu_fac_anual,

  gty_yearprd   TYPE t7piqyearprd,

  BEGIN OF gty_dfkkop,
    opbel   TYPE opbel_kk,
    opupw   TYPE opupw_kk,
    opupk   TYPE opupk_kk,
    opupz   TYPE opupz_kk,
    prctr   TYPE prctr,
    augst   TYPE augst_kk,
    gpart   TYPE gpart_kk,
    abwtp   TYPE abwtp_kk,
    hvorg   TYPE hvorg_kk,
    tvorg   TYPE tvorg_kk,
    stakz   TYPE stakz_kk,
    faedn   TYPE faedn_kk,
    betrh   TYPE betrh_kk,
    persl   TYPE persl_kk,
    augrd   TYPE augrd_kk,
    blart   TYPE blart_kk,
    xblnr   TYPE xblnr_kk,
    psobtyp TYPE psobtyp_ps,
  END OF gty_dfkkop,

  BEGIN OF gty_hrp1000,
    plvar TYPE plvar,
    otype TYPE otype,
    objid TYPE hrobjid,
    istat TYPE istat_d,
    begda TYPE begdatum,
    endda TYPE enddatum,
    langu TYPE langu,
    seqnr TYPE seqnr,
    otjid TYPE otjid,
    stext TYPE stext,
  END OF gty_hrp1000,

  BEGIN OF gty_tb039t,
    category TYPE bu_id_category,
    text     TYPE bu_text40,
  END OF gty_tb039t,

  BEGIN OF gty_timeunitt,
    timeunit  TYPE piqtimeunit,
    timeunitt TYPE piqtimeunitt,
  END OF gty_timeunitt,

  BEGIN OF gty_smstatt,
    smstatus  TYPE piqsmstatus,
    smstatust TYPE piqsmstatust,
  END OF gty_smstatt,

  BEGIN OF gty_reasont,
    reason     TYPE piqreason_gen,
    reasontext TYPE piqreasont,
  END OF gty_reasont,

  BEGIN OF gty_processt,
    process  TYPE piqprocess,
    processt TYPE piqprocess2t,
  END OF gty_processt.

*&---------------------------------------------------------------------*
*   Declaracion de tipos de tablas de datos
*&---------------------------------------------------------------------*
TYPES:
  gtyt_c_param     TYPE TABLE OF gty_c_param,
  gtyt_r_blart     TYPE TABLE OF gty_r_blart,
  gtyt_r_psobtyp   TYPE TABLE OF gty_r_psobtyp,
  gtyt_r_augrd     TYPE TABLE OF gty_r_augrd,
  gtyt_r_hvorg     TYPE TABLE OF gty_r_hvorg,
  gtyt_r_tvorg     TYPE TABLE OF gty_r_tvorg,
  gtyt_certacad_h  TYPE TABLE OF gty_certacad_h,
  gtyt_certacad_pe TYPE TABLE OF gty_certacad_pe,
  gtyt_certacad_pm TYPE TABLE OF gty_certacad_pm,
  gtyt_certacad_sm TYPE TABLE OF gty_certacad_sm,
  gtyt_certacad_na TYPE TABLE OF gty_certacad_na,
  gtyt_certacad_ps TYPE TABLE OF gty_certacad_ps,
  gtyt_certacad_ro TYPE TABLE OF gty_certacad_ro,
  gtyt_certacad_gr TYPE TABLE OF gty_certacad_gr,
  gtyt_but0id      TYPE TABLE OF gty_but0id,
  gtyt_hrp1769     TYPE TABLE OF gty_hrp1769,
  gtyt_hrp1001     TYPE TABLE OF gty_hrp1001,
  gtyt_otjid_varyf TYPE TABLE OF gty_otjid_varyf,
  gtyt_otjid       TYPE TABLE OF gty_otjid,
  gtyt_hrpad530    TYPE TABLE OF gty_hrpad530,
  gtyt_hrp1771     TYPE TABLE OF gty_hrp1771,
  gtyt_hrp1730     TYPE TABLE OF gty_hrp1730,
  gtyt_pensum      TYPE TABLE OF gty_pensum,
  gtyt_adatanr     TYPE TABLE OF gty_adatanr,
  gtyt_hrp1764     TYPE TABLE OF gty_hrp1764,
  gtyt_hrt1764     TYPE TABLE OF gty_hrt1764,
  gtyt_hrp1735     TYPE TABLE OF gty_hrp1735,
  gtyt_hrp1759     TYPE TABLE OF gty_hrp1759,
  gtyt_hrt1759     TYPE TABLE OF gty_hrt1759,
  gtyt_hrp1732     TYPE TABLE OF gty_hrp1732,
  gtyt_tabnr       TYPE TABLE OF gty_tabnr,
  gtyt_hrpad506    TYPE TABLE OF gty_hrpad506,
  gtyt_hrp1724     TYPE TABLE OF gty_hrp1724,
  gtyt_bp_sc_fica  TYPE TABLE OF gty_bp_sc_fica,
  gtyt_fac_anual   TYPE TABLE OF gty_fac_anual,
  gtyt_yearprd     TYPE TABLE OF gty_yearprd,
  gtyt_dfkkop      TYPE TABLE OF gty_dfkkop,
  gtyt_hrp1000     TYPE TABLE OF gty_hrp1000,
  gtyt_tb039t      TYPE TABLE OF gty_tb039t,
  gtyt_timeunitt   TYPE TABLE OF gty_timeunitt,
  gtyt_smstatt     TYPE TABLE OF gty_smstatt,
  gtyt_reasont     TYPE TABLE OF gty_reasont,
  gtyt_processt    TYPE TABLE OF gty_processt.
